
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

android.useAndroidX=true

kotlin.code.style=official

android.enableJetifier=true
org.gradle.warning.mode=all
kotlin.skip.metadata.version.check=true
kotlin.daemon.jvmargs=-Xmx2048m --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED




